#!/usr/bin/env python3
"""Plot BANDGAP_CIRCUIT_TB measurements as four IEEE-columnwidth PDFs.

Emits to ../../svgs/:
* bandgap_iptat.pdf  (PTAT current)
* bandgap_vctat.pdf  (CTAT voltage)
* bandgap_ileak.pdf  (power-down leakage)
* bandgap_iact.pdf   (active supply current)

Also emits sim_params.tex with \\valPtatSpread for the report.
"""

import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _corners import parse_corner_label
from _plotstyle import (
    PROC_COLORS,
    VAR_LW,
    VAR_STYLES,
    init_ieee_style,
    save_overlay_pdf,
)


def _extract(obj: dict) -> dict[str, list[tuple[int, float]]]:
    out = {"iptat": [], "vctat": [], "ileak": [], "iact": []}
    for key, val in obj.items():
        m = re.match(r"(iptat|vctat|ileak|iact)_(-?\d+)$", key)
        if m:
            out[m.group(1)].append((int(m.group(2)), float(val)))
    for v in out.values():
        v.sort()
    return out


def _build_traces(corner_files: list[Path]):
    """Return per-metric list of (label, color, linestyle, linewidth, xs, ys).

    Th/Tl identical -> deduplicated.
    """
    by_metric: dict[str, list] = {k: [] for k in ("iptat", "vctat", "ileak", "iact")}
    seen: set[str] = set()
    for cf in corner_files:
        base = cf.stem
        if re.search(r"_\d+$", base):
            continue
        with cf.open() as fi:
            obj = yaml.safe_load(fi)
        if not obj:
            continue
        label = re.sub(r"^tran_\w*Gt", "", base)
        proc, volt_var = parse_corner_label(label)
        dedup = proc + volt_var
        if dedup in seen:
            continue
        seen.add(dedup)

        c = PROC_COLORS.get(proc, "#999999")
        ls = VAR_STYLES.get(volt_var, "-")
        lw = VAR_LW.get(volt_var, 1.0)
        data = _extract(obj)

        for metric, points in data.items():
            if not points:
                continue
            xs = [t for t, _ in points]
            if metric == "iptat":
                ys = [v * 1e6 for _, v in points]
            elif metric == "vctat":
                ys = [v for _, v in points]
            elif metric == "ileak":
                ys = [abs(v) * 1e9 for _, v in points]
            elif metric == "iact":
                ys = [abs(v) * 1e6 for _, v in points]
            by_metric[metric].append((dedup, c, ls, lw, xs, ys))
    return by_metric


def emit_latex_params(corner_files: list[Path], outpath: Path) -> None:
    """Write LaTeX \\providecommand lines summarising the post-layout PVT sweep."""
    sample_temp = 30
    iptat_at_typ: list[float] = []
    for cf in corner_files:
        stem = cf.stem
        if not stem.startswith("tran_LayGt"):
            continue
        if "Kttmm" in stem or re.search(r"_\d+$", stem):
            continue
        with cf.open() as fi:
            obj = yaml.safe_load(fi)
        if obj and f"iptat_{sample_temp}" in obj:
            iptat_at_typ.append(abs(obj[f"iptat_{sample_temp}"]))
    if not iptat_at_typ:
        return
    mean = sum(iptat_at_typ) / len(iptat_at_typ)
    spread_pct = (max(iptat_at_typ) - min(iptat_at_typ)) / mean * 100
    with outpath.open("w") as f:
        f.write("% Auto-generated by sim/BANDGAP_CIRCUIT_TB/tran.py — do not edit by hand.\n")
        f.write(f"% Post-layout PVT corners (N={len(iptat_at_typ)}) at T={sample_temp} degC.\n")
        f.write(f"\\providecommand{{\\valPtatSpread}}{{{round(spread_pct)}}}\n")


def main(name: str) -> None:
    init_ieee_style()
    yamlfile = Path(name).with_suffix(".yaml")
    outdir = yamlfile.parent
    corner_files = sorted(outdir.glob("tran_*.yaml"))
    if not corner_files:
        print(f"no tran_*.yaml in {outdir.resolve()}", file=sys.stderr)
        return

    emit_latex_params(corner_files, outdir / "sim_params.tex")

    by_metric = _build_traces(corner_files)

    save_overlay_pdf(
        by_metric["iptat"],
        ylabel=r"PTAT current [\unit{\micro\ampere}]",
        outname="bandgap_iptat.pdf",
    )
    save_overlay_pdf(
        by_metric["vctat"],
        ylabel=r"CTAT voltage [\unit{\volt}]",
        outname="bandgap_vctat.pdf",
    )
    # Leakage: y-clip at 2 nA so the hot-corner exponential doesn't flatten
    # the 25 C spec region (<1 nA) into invisibility — handled in a custom
    # helper since the shared overlay function has no ylim hook.
    _save_leak_with_ylim(by_metric["ileak"])

    save_overlay_pdf(
        by_metric["iact"],
        ylabel=r"Active supply current [\unit{\micro\ampere}]",
        outname="bandgap_iact.pdf",
    )


def _save_leak_with_ylim(traces) -> None:
    """Re-emit the leakage panel with y-axis clipped to [0, 2] nA so the
    25 C spec region is readable. Overwrites bandgap_ileak.pdf."""
    import matplotlib.pyplot as plt
    from _plotstyle import (
        IEEE_ACCENT,
        IEEE_COLUMN_WIDTH_IN,
        IEEE_FIG_HEIGHT_IN,
        IEEE_LINE_WIDTH,
    )
    fig, ax = plt.subplots(
        figsize=(IEEE_COLUMN_WIDTH_IN, IEEE_FIG_HEIGHT_IN),
        layout="constrained",
    )
    seen: set[str] = set()
    for label, color, ls, lw, xs, ys in traces:
        kw = {"color": color, "linestyle": ls, "linewidth": lw}
        if label in seen:
            ax.plot(xs, ys, **kw)
        else:
            ax.plot(xs, ys, label=label, **kw)
            seen.add(label)
    ax.axhline(1.0, color=IEEE_ACCENT, linestyle="--",
               linewidth=IEEE_LINE_WIDTH,
               label=r"\qty{1}{\nano\ampere} spec")
    ax.set_xlabel(r"Temperature [\unit{\celsius}]")
    ax.set_ylabel(r"Power-down leakage [\unit{\nano\ampere}]")
    ax.set_ylim(0, 2)
    ax.grid(visible=True)
    ax.legend(loc="best", frameon=False, ncol=2, fontsize=7)
    out = Path(__file__).resolve().parents[2] / "svgs" / "bandgap_ileak.pdf"
    fig.savefig(out)
    plt.close(fig)
    print(f"saved {out} (clipped 0-2 nA)")


if __name__ == "__main__":
    name = sys.argv[1] if len(sys.argv) > 1 else "output_tran/tran"
    main(name)
