#!/usr/bin/env python3
"""Plot OSCILLATOR_TB measurements as four IEEE-columnwidth PDFs.

Emits to ../../svgs/:
* osc_freq.pdf       (oscillator frequency vs temperature)
* osc_err1pt.pdf     (1-pt calibration residual error vs temperature)
* osc_iact.pdf       (active supply current vs temperature)
* osc_err2pt.pdf     (2-pt calibration residual error vs temperature)

Also emits sim_params.tex with \\valKerrone / \\valKerrtwo.
"""

import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _corners import parse_corner_label
from _plotstyle import (
    IEEE_ACCENT,
    IEEE_COLUMN_WIDTH_IN,
    IEEE_FIG_HEIGHT_IN,
    IEEE_LINE_WIDTH,
    PROC_COLORS,
    VAR_LW,
    VAR_STYLES,
    init_ieee_style,
    save_overlay_pdf,
)


def _parse_measurements(obj: dict):
    t1, t2, idd = {}, {}, {}
    for key, val in obj.items():
        if key.startswith("t1_"):
            t1[int(key.split("_")[1])] = float(val)
        elif key.startswith("t2_"):
            t2[int(key.split("_")[1])] = float(val)
        elif key.startswith("idd_"):
            idd[int(key.split("_")[1])] = float(val)
    return t1, t2, idd


def _parse_corner(cf: Path):
    base = cf.stem
    if re.search(r"_\d+$", base):
        return None
    with cf.open() as fi:
        obj = yaml.safe_load(fi)
    if not obj:
        return None
    label = re.sub(r"^tran_\w*Gt", "", base)
    proc, volt_var = parse_corner_label(label)
    t1, t2, idd = _parse_measurements(obj)
    temps = sorted(t for t in t1 if t in t2)
    freq = [1.0 / ((t2[t] - t1[t]) / 4.0) / 1e6 for t in temps]
    return label, proc, volt_var, temps, freq, idd


def _find_nominal_slope(corners) -> float | None:
    def slope_of(temps, freq):
        t = np.array(temps, dtype=float)
        f = np.array(freq)
        mask = (t >= -40) & (t <= 125)
        if mask.sum() < 2:
            return None
        return float(np.polyfit(f[mask], t[mask], 1)[0])

    for c in corners:
        _l, proc, volt, temps, freq, _idd = c
        if proc == "Ktt" and volt == "Vt":
            s = slope_of(temps, freq)
            if s is not None:
                return s
    for c in corners:
        s = slope_of(c[3], c[4])
        if s is not None:
            return s
    return None


def _save_err_pdf(traces, outname: str, accent_pm: float):
    """Plot calibration error vs temperature with ±accent_pm dashed lines and
    0–70 °C spec-scope markers. Each trace is (label, color, ls, lw, xs, ys)."""
    fig, ax = plt.subplots(
        figsize=(IEEE_COLUMN_WIDTH_IN, IEEE_FIG_HEIGHT_IN),
        layout="constrained",
    )
    seen: set[str] = set()
    for label, color, ls, lw, xs, ys in traces:
        kw = {"color": color, "linestyle": ls, "linewidth": lw}
        if label in seen:
            ax.plot(xs, ys, **kw)
        else:
            ax.plot(xs, ys, label=label, **kw)
            seen.add(label)
    ax.axhline(accent_pm, color=IEEE_ACCENT, linestyle="--",
               linewidth=IEEE_LINE_WIDTH,
               label=rf"$\pm$\qty{{{accent_pm:g}}}{{\celsius}} spec")
    ax.axhline(-accent_pm, color=IEEE_ACCENT, linestyle="--",
               linewidth=IEEE_LINE_WIDTH)
    ax.axvline(0, color="#9ca0b0", linestyle=":", linewidth=IEEE_LINE_WIDTH)
    ax.axvline(70, color="#9ca0b0", linestyle=":", linewidth=IEEE_LINE_WIDTH)
    ax.set_xlabel(r"Temperature [\unit{\celsius}]")
    ax.set_ylabel(r"Error [\unit{\celsius}]")
    ax.grid(visible=True)
    ax.legend(loc="best", frameon=False, ncol=2, fontsize=7)
    out = Path(__file__).resolve().parents[2] / "svgs" / outname
    fig.savefig(out)
    plt.close(fig)
    print(f"saved {out}")


def emit_latex_params(corners, nominal_slope, outpath: Path) -> None:
    scope_lo, scope_hi = 0, 70
    cal_lo, cal_hi = 25, 85
    err_one, err_two = 0.0, 0.0
    for _l, proc, _v, temps, freq, _i in corners:
        if "mm" in proc or len(temps) < 2:
            continue
        t = np.array(temps, dtype=float)
        f = np.array(freq)
        in_scope = (t >= scope_lo) & (t <= scope_hi)
        if not in_scope.any():
            continue
        f_lo = np.interp(cal_lo, t, f)
        f_hi = np.interp(cal_hi, t, f)
        if nominal_slope is not None:
            offset = cal_lo - nominal_slope * f_lo
            err_one = max(err_one, float(np.max(np.abs(
                (nominal_slope * f + offset - t)[in_scope]))))
        slope_two = (cal_hi - cal_lo) / (f_hi - f_lo)
        offset_two = cal_lo - slope_two * f_lo
        err_two = max(err_two, float(np.max(np.abs(
            (slope_two * f + offset_two - t)[in_scope]))))
    with outpath.open("w") as fo:
        fo.write("% Auto-generated by sim/OSCILLATOR_TB/tran.py — do not edit by hand.\n")
        fo.write(f"% Worst-case 1-pt / 2-pt cal residual in {scope_lo}–{scope_hi} °C, per spec.\n")
        if nominal_slope is not None:
            fo.write(f"\\providecommand{{\\valKerrone}}{{{err_one:.1f}}}\n")
        fo.write(f"\\providecommand{{\\valKerrtwo}}{{{err_two:.1f}}}\n")


def main(name: str) -> None:
    init_ieee_style()
    yamlfile = Path(name).with_suffix(".yaml")
    outdir = yamlfile.parent
    corner_files = sorted(outdir.glob("tran_*.yaml"))

    corners = []
    seen: set[str] = set()
    for cf in corner_files:
        r = _parse_corner(cf)
        if r is None:
            continue
        dedup = r[1] + r[2]
        if dedup in seen:
            continue
        seen.add(dedup)
        corners.append(r)

    nominal_slope = _find_nominal_slope(corners)
    emit_latex_params(corners, nominal_slope, outdir / "sim_params.tex")

    freq_traces, iact_traces, err1_traces, err2_traces = [], [], [], []
    for _l, proc, volt, temps, freq, idd in corners:
        c = PROC_COLORS.get(proc, "#999999")
        ls = VAR_STYLES.get(volt, "-")
        lw = VAR_LW.get(volt, 1.0)
        dedup = proc + volt

        if temps and freq:
            freq_traces.append((dedup, c, ls, lw, list(temps), list(freq)))
        idd_temps = sorted(idd.keys())
        if idd_temps:
            iact_traces.append((dedup, c, ls, lw, idd_temps,
                                [abs(idd[t]) * 1e6 for t in idd_temps]))

        if len(temps) >= 2:
            t = np.array(temps, dtype=float)
            f = np.array(freq)
            f25 = float(np.interp(25, t, f))
            f85 = float(np.interp(85, t, f))
            if nominal_slope is not None:
                offset1 = 25 - nominal_slope * f25
                err1 = (nominal_slope * f + offset1 - t).tolist()
                err1_traces.append((dedup, c, ls, lw, list(temps), err1))
            slope2 = (85 - 25) / (f85 - f25)
            offset2 = 25 - slope2 * f25
            err2 = (slope2 * f + offset2 - t).tolist()
            err2_traces.append((dedup, c, ls, lw, list(temps), err2))

    save_overlay_pdf(
        freq_traces,
        ylabel=r"Frequency [\unit{\mega\hertz}]",
        outname="osc_freq.pdf",
    )
    save_overlay_pdf(
        iact_traces,
        ylabel=r"Active supply current [\unit{\micro\ampere}]",
        outname="osc_iact.pdf",
    )
    if err1_traces:
        _save_err_pdf(err1_traces, "osc_err1pt.pdf", accent_pm=10.0)
    _save_err_pdf(err2_traces, "osc_err2pt.pdf", accent_pm=5.0)


if __name__ == "__main__":
    name = sys.argv[1] if len(sys.argv) > 1 else "output_tran/tran"
    main(name)
